name: "Delete Workflow Runs"

on:
  workflow_dispatch:
    inputs:
      status_pattern:
        description: "Select which run status/conclusion to delete"
        required: true
        default: "failure"
        type: choice
        options:
          - "failure"
          - "success"
          - "cancelled"
          - "skipped"
          - "failure|cancelled|skipped" # Delete non-successful runs
          - ".*"                         # Delete ALL runs

jobs:
  del_runs:
    name: "Purge Targeted Workflow Runs"
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete Workflow Runs Matching Pattern
        uses: Mattraks/delete-workflow-runs@9835e4abbefe04992885a989df6e3f61ddd60117
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: ${{ inputs.status_pattern }}
          