name: "Infrastructure as Code"

on:
  workflow_call:

jobs:
  iac-and-policy:
    name: "IaC & OPA Policy Enforcement"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: Vharse/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v4.4.0
        with:
          persist-credentials: false

      - name: Setup Open Policy Agent
        uses: ./.github/actions/setup-opa
        with:
          version: latest

      - name: Evaluate OPA Rego Policies
        run: |
          if [ -d "policies/opa" ]; then
            opa eval --data policies/opa/ "data"
          fi
