name: "IaC & Policy Enforcement Workflow"

on:
  workflow_call:

jobs:
  iac-and-policy:
    name: "IaC & OPA Policy Enforcement"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Setup Open Policy Agent
        uses: open-policy-agent/setup-opa@b2b258e089860efaadaaf71bf6e3aecb4a3eeff1
        with:
          version: latest

      - name: Evaluate OPA Rego Policies
        run: |
          if [ -d "policies/opa" ]; then
            opa eval --data policies/opa/ "data"
          fi