name: "SAST, Secret Scanning & Code Quality Workflow"

on:
  workflow_call:
    secrets:
      SEMGREP_APP_TOKEN:
        required: false
      SONAR_HOST:
        required: false
      SONAR_TOKEN:
        required: false

jobs:
  sast-secrets-and-quality:
    name: "SAST, Secrets & SonarQube"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    outputs:
      semgrep-json-path: semgrep-results.json
      gitleaks-json-path: gitleaks-results.json
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v3
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --report-format json --report-path gitleaks-results.json

      - name: Semgrep SAST Scan
        uses: semgrep/semgrep-action@v1
        continue-on-error: true
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        with:
          generate-sarif: "1"
          config: auto

      - name: Rename Semgrep Output for Ingestion
        run: |
          if [ -f "semgrep.sarif" ]; then
            cp semgrep.sarif semgrep-results.json
          elif [ -f "semgrep-results.json" ]; then
            true
          else
            echo "{}" > semgrep-results.json
          end

      - name: SonarQube Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            "-Dsonar.projectKey=Vharse_Devsecops-Automation-Engine"
            "-Dsonar.projectName=${{ github.event.repository.name || github.repository }}"
            "-Dsonar.organization=vharse"
            "-Dsonar.python.version=3.13"
            "-Dsonar.sources=."
            "-Dsonar.exclusions=**/node_modules/**,**/vendor/**,**/.venv/**"
            "-Dsonar.issue.ignore.multicriteria=e1"
            "-Dsonar.issue.ignore.multicriteria.e1.ruleKey=docker:S6596"
            "-Dsonar.issue.ignore.multicriteria.e1.resourceKey=src/Dockerfile"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload SAST & Secret Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sast-secret-reports
          path: |
            semgrep-results.json
            gitleaks-results.json