name: "OpenSSF Scorecard Workflow"

on:
  workflow_call:

jobs:
  repo-scorecard:
    name: "OpenSSF Security Posture Evaluation"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout Repository
        uses: Vharse/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v4.2.2
        with:
          fetch-depth: 0

      - name: Run OpenSSF Scorecard
        uses: ./.github/actions/scorecard-action
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: ${{ github.ref == 'refs/heads/main' }}

      - name: Upload SARIF to GitHub Security Tab
        uses: ./.github/actions/codeql-action/init
        with:
          sarif_file: scorecard-results.sarif
