name: "OpenSSF Scorecard Workflow"

on:
  workflow_call:

jobs:
  repo-scorecard:
    name: "OpenSSF Security Posture Evaluation"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@6f5948dfacef28e207b48d0905cf90c03365536d
        with:
          sarif_file: scorecard-results.sarif