name: "Secret Scanning"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  secret-scanning:
    name: "Gitleaks Secret Scan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    outputs:
      gitleaks-json-path: gitleaks-results.json
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Gitleaks CLI
        run: |
          VERSION="8.24.3"
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
          tar -zxvf gitleaks_${VERSION}_linux_x64.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/
          rm gitleaks_${VERSION}_linux_x64.tar.gz

      - name: Run Gitleaks Detection
        run: |
          gitleaks detect --source=. --verbose --redact --report-path=gitleaks-results.json

      - name: Upload Secret Artifacts
        if: always()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: secret-reports
          path: gitleaks-results.json
