name: "Secret Scanning"

on:
  workflow_call:

jobs:
  secret-scanning:
    name: "Gitleaks Secret Scan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    outputs:
      gitleaks-json-path: gitleaks-results.json
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --report-format json --report-path gitleaks-results.json

      - name: Upload Secret Artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: secret-reports
          path: gitleaks-results.json
