name: Vharse DevOps Security Guard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    uses: ./.github/workflows/sast.yml
    permissions:
      contents: read
      security-events: write
      actions: read
      checks: write
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml
    permissions:
      contents: read
      security-events: write
      actions: read
      checks: write

  container-and-sbom:
    uses: Vharse/Devsecops-Automation-Engine/.github/workflows/container-sbom.yml@3f962b2d03501134c40a9fd188ca36477593eeb7
    permissions:
      contents: read
      security-events: write
      actions: read
      checks: write
    secrets:
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}

  iac-and-opa:
    uses: Vharse/Devsecops-Automation-Engine/.github/workflows/iac-opa.yml@3f962b2d03501134c40a9fd188ca36477593eeb7
    permissions:
      contents: read
      security-events: write
      actions: read
      checks: write

  scorecard-audit:
    uses: ./.github/workflows/scorecard.yml
    permissions:
      contents: read
      security-events: write
      actions: read
      checks: write
      id-token: write

  siem-telemetry:
    uses: Vharse/Devsecops-Automation-Engine/.github/workflows/siem-telemetry.yml@3f962b2d03501134c40a9fd188ca36477593eeb7
    permissions:
      contents: read
      actions: read
    secrets:
      ELASTIC_HOST: ${{ secrets.ELASTIC_HOST }}
      ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}

  defectdojo-ingestion:
    needs: [sast, secret-scanning, container-and-sbom, iac-and-opa, scorecard-audit]
    if: always()
    uses: Vharse/Devsecops-Automation-Engine/.github/workflows/defectdojo-sync.yml@4c8abe68e5cc52c311f8a913e942d5fe388a5bdc
    permissions:
      contents: read
      actions: read
    with:
      sast_job_needed: true
      container_job_needed: true
    secrets:
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
