name: Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-security-engine:
    uses: Vharse/Devsecops-Automation-Engine/.github/workflows/security-engine.yml@main
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
      checks: write
    secrets: inherit
